### ISSUE TITLE
The documentation for Data.Char should contain examples of how you write the literals

### ISSUE THREAD

**Issue by tomjaguarpaw** [tomjaguarpaw/tilapia#128]
https://hackage.haskell.org/package/base-4.16.0.0/docs/Prelude.html#t:Char

See https://www.reddit.com/r/haskellquestions/comments/yk8ip6/match_against_non_symbol_ascii_characters/.compact

**Comment by Bodigrim** [comment]
I think it's better now: https://hackage.haskell.org/package/base-4.19.0.0/docs/Prelude.html#t:Char

**Comment by tomjaguarpaw** [comment]
Nice, thanks!
