### ISSUE TITLE
something broke some doctests on ghc 9.10

### ISSUE THREAD

**Issue by ysangkok** [tomjaguarpaw/tilapia#138]
I don't really understand what's going on here. I would add it to the breakage repo but I don't know what to write.

* https://github.com/GetShopTV/swagger2/issues/254
* https://github.com/haskell-servant/servant/pull/1765#issuecomment-2162183465

**Comment by ysangkok** [comment]
Oh, it's just because the wording of the error message changed. Not sure if this is something tracked in this repo @tomjaguarpaw ?

**Comment by tomjaguarpaw** [comment]
I think changes to error messages are not "breaking" enough to be tracked in the breakage inventory.

**Comment by ysangkok** [comment]
Ok, good! Thanks for the clarification, I will close this.
