### ISSUE TITLE
9.8.4 breaks compilation of ghc/hls

### ISSUE THREAD

**Issue by hasufell** [tomjaguarpaw/tilapia#139]
* https://github.com/haskell/deepseq/issues/105
* https://gitlab.haskell.org/ghc/ghc/-/issues/25411
* https://github.com/haskell/haskell-language-server/pull/4459

This is due to a new deepseq identifier. I don't think the exposure is large.

**Comment by tomjaguarpaw** [comment]
Thanks! Closed by https://github.com/tomjaguarpaw/tilapia/commit/15e4cfe19c92631ec82ec7fb7cf1fa10ec50c3bd
