### ISSUE TITLE
9.8.4 ghc getKey

### ISSUE THREAD

**Issue by juhp** [tomjaguarpaw/tilapia#140]
This broke 3 packages in Stackage Nightly:

```
           • Couldn't match type ‘GHC.Word.Word64’ with ‘Int’                                                                       
             Expected: GHC.Types.Unique.Unique -> Int             
               Actual: GHC.Types.Unique.Unique -> GHC.Word.Word64                                                                   
```

- https://github.com/clash-lang/clash-compiler/issues/2852
- https://github.com/jonascarpay/calligraphy/issues/40
- https://github.com/konn/ghc-typelits-presburger/issues/30

**Comment by tomjaguarpaw** [comment]
Thanks! Closed by https://github.com/tomjaguarpaw/tilapia/commit/15e4cfe19c92631ec82ec7fb7cf1fa10ec50c3bd
