### ISSUE TITLE
Uploading to Hackage

### ISSUE THREAD

**Issue by georgefst** [tomjaguarpaw/tilapia#34]
I was about to post a rant about this to Reddit (and I still might...), but I suddenly remembered this project and figured this is the kind of problem worth logging here:

There's an awful lot of incidental complexity in the process of simply uploading a package to Hackage. Over the eighteen months since I published my first library, I've gradually constructed the following bit of bash (it's probably not perfect, not least since `--enable-documentation` triggers a rebuild of all transitive dependencies):

```bash
function hackage { # Upload the latest version of the package in the current directory
  cabal configure --enable-documentation
  cabal sdist
  cabal haddock --haddock-for-hackage
  USERNAME='GeorgeThomas'
  read -rsp 'Hackage password: ' PASSWORD
  find dist-newstyle/sdist -name '*.tar.gz' | sort -r | head -n1 | xargs \
    cabal upload --publish -u "$USERNAME" -p "$PASSWORD"
  find dist-newstyle -name '*-docs.tar.gz'  | sort -r | head -n1 | xargs \
    cabal upload --publish -u "$USERNAME" -p "$PASSWORD" --doc
}
```

It's suddenly struck me that this is insane, and I don't know how we expect newcomers to figure this stuff out.

**Comment by tomjaguarpaw** [comment]
> figured this is the kind of problem worth logging here

Yes, a perfect one, thanks!

I have a couple of questions

1. What purpose does `--enable-documentation` serve here? One can run `cabal haddock` even if `--enable-documentation` was not provided in `configure` (and I generally don't explicitly run `configure` anyway).

2. It's very painful that one has to `find` and `sort` to discover the filename one wants! Do you think there ought to be some command (`cabal what-haddocks-did-i-just-generate` or whatever) that tells you in which location the generated Haddocks and sdist are to be found?

**Comment by tomjaguarpaw** [comment]
> I was about to post a rant about this to Reddit (and I still might...)

I think I'd probably caution against that for now. This issue seems like something we could make good progress towards fixing without needing the impetus of an angry community.  I'd rather cabal not develop the reputation of "well cabal hell was fixed but the bits still don't work properly together", at least not until I've had a good opportunity to do what's necessary to avoid that!

**Comment by tomjaguarpaw** [comment]
> What purpose does --enable-documentation serve here?

Coincidental [recent comment on same topic](https://github.com/vrom911/vrom911.github.io/issues/52#issuecomment-708266479).

**Comment by georgefst** [comment]
> What purpose does --enable-documentation serve here?

That's the last bit I added, after getting a list of "could not find links" errors at the haddock step. On reflection, I don't think it's necessary, and Hackage has definitely found links in the past without that flag. Perhaps the warnings are meaningless when `--haddock-for-hackage` is on? I'll try to investigate that.

> It's very painful that one has to find and sort to discover the filename one wants!

I really think `upload` ought to imply `sdist`, and `upload --doc` imply `haddock --haddock-for-hackage`, in the same way that `run` implies `build`. Indeed perhaps `upload` should even imlpy `upload --doc` since I think the Cabal/Hackage maintainers communicated at some point that that's what we should always be doing.

> I think I'd probably caution against that for now. This issue seems like something we could make good progress towards fixing without needing the impetus of an angry community. I'd rather cabal not develop the reputation of "well cabal hell was fixed but the bits still don't work properly together", at least not until I've had a good opportunity to do what's necessary to avoid that!

Yup, that's pretty much why I didn't. I've spent a lot of time trying to convince people that "you can just use cabal now - everything's been fixed" and I don't want to undo any of that over something relatively minor. The alternative was to phrase it as more of a question - "this feels overly complicated - what's your process for uploading packages?" but that would still probably attract some ranters.

**Comment by tomjaguarpaw** [comment]
> I really think `upload` ought to imply `sdist`, and `upload --doc` imply `haddock --haddock-for-hackage`

Yes, that makes a lot of sense.

> perhaps `upload` should even imply `upload --doc` since I think the Cabal/Hackage maintainers communicated at some point that that's what we should always be doing

Oh, what did they mean by that? That we should always upload our own docs rather than rely on their doc builder? I've never uploaded my own docs!

> I've spent a lot of time trying to convince people that "you can just use cabal now - everything's been fixed" and I don't want to undo any of that over something relatively minor. 

Yes, same here.

**Comment by georgefst** [comment]
> Oh, what did they mean by that? That we should always upload our own docs rather than rely on their doc builder? I've never uploaded my own docs!

I'll see if I can find where I got that from - maybe it was a less official recommendation than I'm remembering. But sometimes the docs just don't build, and it's unclear why. Uploading them manually never seems to hurt.

**Comment by tomjaguarpaw** [comment]
> But sometimes Hackage just doesn't build the docs, and it's unclear why. 

Yeah Hackage was *very* slow to build docs back a couple of years or so. These days I find it pretty quick, say, a few hours from upload.

**Comment by georgefst** [comment]
> What purpose does --enable-documentation serve here?

Just remembered. That came from [this thread](https://www.reddit.com/r/haskell/comments/debpui/how_to_install_package_documentation/). But I've a suspicion Cabal/Hackage/Haddock has improved the situation since then. Will test when I can.

**Comment by georgefst** [comment]
So, I've played around with this a bit (Cabal 3.2). Bizarrely, `upload --doc` seems to sort of imply `haddock` but without passing the right flags, and with a confusing error message:

```
> cabal upload --publish --doc                                                                                                                                                                                                                                                                ~/personal/svgone
No documentation tarball specified. Building a documentation tarball with
default settings...
If you need to customise Haddock options, run 'haddock --for-hackage' first to
generate a documentation tarball.
Resolving dependencies...
Warning: solver failed to find a solution:
Could not resolve dependencies:
[__0] trying: svgone-0.1.0.0 (user goal)
[__1] unknown package: safe (dependency of svgone)
[__1] fail (backjumping, conflict set: safe, svgone)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: svgone, safe
Trying configure anyway.
Configuring svgone-0.1.0.0...
cabal: Encountered missing or private dependencies:
extra >=1.7.9 && <1.8,
generic-lens ==2.0.*,
lens >=4.19.2 && <4.20,
linear >=1.21.3 && <1.22,
pretty-simple >=4.0.0 && <4.1,
reanimate-svg >=0.13.0 && <0.14,
safe >=0.3.19 && <0.4
```

The solution was to run `cabal haddock --haddock-for-hackage`, then explicitly pass `upload` the path to the generated tarball. This does trigger a rebuild of dependencies with documentation, so at least the `configure` step is indeed unnecessary.

Incidentally, I left it overnight to see if Hackage would build docs, and it hasn't done so yet (for a *very* small library).

**Comment by tomjaguarpaw** [comment]
> I left it overnight to see if Hackage would build docs, and it hasn't done so yet

Seems like it has now?

https://hackage.haskell.org/package/svgone-0.1.0.0/docs/Svgone.html

Doc generation can be slow but I don't think I've ever known it to actually fail (outside of situations that were genuinely acknowledged to be cases of broken infrastructure).

**Comment by georgefst** [comment]
> Seems like it has now?

No, that's from me uploading manually with the steps outlined above. And now that I look again, it hasn't found any links for third-party libraries. Eugh...

I'll try to wait longer for the docs to build on the server next time. But even if that does always work, it's far from ideal if it's the only option and it takes a few days.

(this thread is getting messy - I'll try and summarise the way forward once I feel I've got the full picture)

**Comment by tomjaguarpaw** [comment]
>> Seems like it has now?

> No, that's from me uploading manually with the steps outlined above.


Oh I see. This is hard to track down if reproducing the problem is just waiting indefinitely for something to perhaps happen! Do you know if there's a public view into the queue of docs waiting to be built?

**Comment by georgefst** [comment]
> Do you know if there's a public view into the queue of docs waiting to be built?

Not that I know of. But then I only recently found out that the server even builds docs itself...

**Comment by kindaro** [comment]
You can see reports if you add `…/reports` to your link.

https://hackage.haskell.org/package/svgone-0.1.0.0/reports/

An _(apparently successful)_ example from another package:

https://hackage.haskell.org/package/mime-mail-ses-0.4.3/reports/

**Comment by georgefst** [comment]
That is very useful, thanks @kindaro.

And to be fair, there is actually a link on the top-level documentation page for the package. I'd just never thought to look for it.

**Comment by georgefst** [comment]
Of course, it would be great if Hackage sent email notifications or something upon build failure. Another thing to put on the wishlist...

**Comment by kindaro** [comment]
Glad to be of service.

It would be nice if we could also see the build machine's queue, so that you could at least know that the build is scheduled when you have uploaded the package, and observe it move forward in the queue over time.

**Comment by georgefst** [comment]
It turns out the reason I'd always assumed the manual doc upload to be necessary is because the first library I ever published required a C library (`libevdev`) that wasn't installed on the Hackage builders.

So all that's actually needed is `cabal upload --publish $(cabal sdist | tail -n 1)`

Therefore, ultimately, I think the one useful change to Cabal would be for `cabal upload` to automatically run `cabal sdist` first, and provide the path to the tarball.

**Comment by georgefst** [comment]
> Therefore, ultimately, I think the one useful change to Cabal would be for `cabal upload` to automatically run `cabal sdist` first, and remember the path to the tarball internally. Requiring the user to care about locations of files in `dist-newstyle` is bad UX.

Which has now been opened as https://github.com/haskell/cabal/issues/7566. So perhaps this could be closed.

**Comment by tomjaguarpaw** [comment]
Ah, well spotted.
