### ISSUE TITLE
Who owns https://www.haskell.org/cabal/?

### ISSUE THREAD

**Issue by tomjaguarpaw** [tomjaguarpaw/tilapia#46]
The source for https://www.haskell.org/cabal/ does not seem to appear in https://github.com/haskell-infra/www.haskell.org.  I asked where it is: https://github.com/haskell-infra/www.haskell.org/issues/47.

**Comment by tomjaguarpaw** [comment]
Waiting for: A response on https://github.com/haskell-infra/www.haskell.org/issues/47

**Comment by fgaz** [comment]
https://github.com/haskell/cabal-website, and I think @gbaz has the keys

**Comment by tomjaguarpaw** [comment]
Super, thanks!
