### ISSUE TITLE
GSOC Suggestions

### ISSUE THREAD

**Issue by ketzacoatl** [tomjaguarpaw/tilapia#60]
Between https://summer.haskell.org/ideas.html and https://discourse.haskell.org/t/gsoc-2021-call-for-ideas/1775, it seems there isn't much in the way of great suggestions for students interested in contributing to Haskell through GSOC.

It seems like a good idea to brainstorm and build a list here together with others, that we could share with the GSOC maintainer/shepherd. What do you think?

cc @tomjaguarpaw

**Comment by tomjaguarpaw** [comment]
It seems like writing docs is out of scope, but writing code examples or improving the APIs of tools and libraries would be in scope.

> The GSoC rules state that it must involve writing code primarily (as opposed to 
docs). 

One thing I would like to see is a well-typed interface to `process` along the lines of https://github.com/haskell/process/compare/master...tomjaguarpaw:type-level-maybe, but perhaps the challenge there is more one of persuasion to adopt it than a coding one per se.

**Comment by ketzacoatl** [comment]
Some ideas I have, initially:
* our crypto libraries need work, missing functions, better examples, probably tests and bugfixes that result
* we could seek out the various "state of haskell" reports, such as https://www.haskellforall.com/2016/02/state-of-haskell-ecosystem-february.html (there are newer ones, and by others as well)
* https://github.com/NorfairKing/haskell-WAT is full of interesting threads to pull on

**Comment by ketzacoatl** [comment]
> One thing I would like to see is a well-typed interface to process along the lines of haskell/process@master...tomjaguarpaw:type-level-maybe, but perhaps the challenge there is more one of persuasion to adopt it than a coding one per se.

Have you gotten to use `typed-process`? Here's the readme: https://github.com/fpco/typed-process#readme

**Comment by ketzacoatl** [comment]
Also from the GSOC doc:
> You can contribute ideas by sending a pull request to our github repository. If you just want to discuss a possible idea, please contact us.

In terms of effort:

> Projects should be concrete and small enough in scope such that they can be finished by a student in three months. Past experience has shown that keeping projects “small” is almost always a good idea.

> Important change for 2021: In the past, GSoC projects were expected to take up the equivalent of full time employment for a student. However, in 2021, this has been reduced to half time positions: students are expected to work around 175 hours in a 10 week period.

**Comment by tomjaguarpaw** [comment]
> Have you gotten to use typed-process?

Thanks, I should have a closer look at typed process. So far I only focused on one specific aspect of type unsafety of process.

**Comment by tomjaguarpaw** [comment]
I have had a good experience contributing docs to typed-process

* https://github.com/fpco/typed-process/pull/34
* https://github.com/fpco/typed-process/pull/35
* https://github.com/fpco/typed-process/pull/36

**Comment by ketzacoatl** [comment]
I guess one flaw in my initial thinking was that the GSoC projects rely on a mentor, so it seems weird to push ideas out to projects that need to mentor the GSoC students themselves. These ideas need to come from the projects.
