### ISSUE TITLE
Outsider confusion

### ISSUE THREAD

**Issue by tomjaguarpaw** [tomjaguarpaw/tilapia#82]
https://news.ycombinator.com/item?id=26083269

> Should I use an alternate prelude? What string type should I use? Should I use lens? What package manager and build system should I use? What IDE plug-in works the best? What language extensions should I use? Should I make use of laziness, or try to avoid it? Are linear types a thing yet and should I use them?
>
> And on and on the questions go.. these aren’t questions that move forward the product, but just an endless list of boring details to figure out.

**Comment by MatthijsBlom** [comment]
Duplicate of #62.

**Comment by tomjaguarpaw** [comment]
Thanks! Closing.
