### ISSUE TITLE
HLS autocompletion doesn't seem to work for qualified names

### ISSUE THREAD

**Issue by nrnrnr** [tomjaguarpaw/tilapia#95]
Using Emacs `lsp-mode` with the Haskell Language Server, it doesn't seem to complete qualified names.  At least not out of the box. If someone who can fix it appears, I can whip up a minimal example.

**Comment by jneira** [comment]
maybe it worths to open an issue in hls? @michaelpj uses emacs iirc, maybe he knows more about this and if the issue belongs to lsp-emacs or hls

**Comment by noughtmare** [comment]
Should this be closed now that https://github.com/haskell/haskell-language-server/issues/2082 is closed?

**Comment by tomjaguarpaw** [comment]
OK, thanks!
