### ISSUE TITLE
Data.ByteString should export toStrict/fromStrict

### ISSUE THREAD

**Issue by tomjaguarpaw** [tomjaguarpaw/tilapia#99]
`Data.ByteString.Lazy` export `toStrict`/`fromStrict` but `Data.ByteString` doesn't. Why not?

**Comment by kindaro** [comment]
Because `Data.ByteString.Lazy` imports `Data.ByteString` and importing also the other way around will mean cyclic imports. There is a provision for cyclic imports in GHC, so in principle it is possible to fix this.

**Comment by tomjaguarpaw** [comment]
I suspect the definitions should be in `Internal` modules, and the external API modules just re-export things from there.

**Comment by Bodigrim** [comment]
This is fixed: https://hackage.haskell.org/package/bytestring-0.11.4.0/docs/Data-ByteString.html#v:fromStrict

**Comment by tomjaguarpaw** [comment]
Great, thanks!
